// src/qna.ts
export const QNA_DATA = [
  { question: "What is the capital of France?", answer: "Paris" },
  { question: "Who wrote Hamlet?", answer: "William Shakespeare" },
  { question: "What is the speed of light?", answer: "299,792 km per second" },
  { question: "What is 2 + 2?", answer: "4" },
  { question: "What is the largest planet?", answer: "Jupiter" },
  { question: "What is the chemical symbol for gold?", answer: "Au" },
  { question: "In which year did World War II end?", answer: "1945" },
  {
    question: "What is the tallest mountain in the world?",
    answer: "Mount Everest",
  },
  { question: "Who painted the Mona Lisa?", answer: "Leonardo da Vinci" },
  { question: "What is the largest ocean on Earth?", answer: "Pacific Ocean" },
  { question: "How many continents are there?", answer: "7" },
  { question: "What is the square root of 64?", answer: "8" },
  { question: "Who invented the telephone?", answer: "Alexander Graham Bell" },
  { question: "What is the freezing point of water in Celsius?", answer: "0" },
  { question: "Which planet is known as the Red Planet?", answer: "Mars" },
  { question: "What is the capital of Japan?", answer: "Tokyo" },
  {
    question: "Who was the first president of the United States?",
    answer: "George Washington",
  },
  { question: "What is the largest mammal?", answer: "Blue whale" },
  { question: "How many sides does a hexagon have?", answer: "6" },
  { question: "What is the main component of the Sun?", answer: "Hydrogen" },
  {
    question: "In which country would you find the Great Pyramid of Giza?",
    answer: "Egypt",
  },
  {
    question: "What is the hardest natural substance on Earth?",
    answer: "Diamond",
  },
  { question: "How many bones are in the human body?", answer: "206" },
  {
    question: "What is the currency of the United Kingdom?",
    answer: "Pound sterling",
  },
  { question: "Who discovered gravity?", answer: "Isaac Newton" },
  {
    question: "What is the boiling point of water in Fahrenheit?",
    answer: "212",
  },
  { question: "Which language is spoken in Brazil?", answer: "Portuguese" },
  { question: "What is the capital of Canada?", answer: "Ottawa" },
  { question: "How many players are on a baseball team?", answer: "9" },
  {
    question: "What is the largest desert in the world?",
    answer: "Sahara Desert",
  },
  { question: "Who wrote 'To Kill a Mockingbird'?", answer: "Harper Lee" },
  { question: "What is the smallest prime number?", answer: "2" },
  { question: "Which planet has the most moons?", answer: "Jupiter" },
  { question: "What is the capital of Australia?", answer: "Canberra" },
  { question: "How many colors are in a rainbow?", answer: "7" },
  { question: "What is the chemical formula for water?", answer: "H₂O" },
  {
    question: "Who was the first person to walk on the moon?",
    answer: "Neil Armstrong",
  },
  { question: "What is the longest river in the world?", answer: "Nile River" },
  { question: "Which country is home to the kangaroo?", answer: "Australia" },
  { question: "What is the capital of Italy?", answer: "Rome" },
  { question: "How many teaspoons are in a tablespoon?", answer: "3" },
  { question: "What is the largest organ in the human body?", answer: "Skin" },
  { question: "Who wrote 'Romeo and Juliet'?", answer: "William Shakespeare" },
  { question: "What is the currency of Japan?", answer: "Yen" },
  {
    question: "Which gas do plants absorb from the atmosphere?",
    answer: "Carbon dioxide",
  },
  { question: "What is the capital of Spain?", answer: "Madrid" },
  { question: "How many years are in a century?", answer: "100" },
  { question: "What is the closest star to Earth?", answer: "Sun" },
  {
    question: "Who is known as the father of computers?",
    answer: "Charles Babbage",
  },
  { question: "What is the capital of China?", answer: "Beijing" },
  { question: "How many planets are in our solar system?", answer: "8" },
  { question: "What is the chemical symbol for oxygen?", answer: "O" },
  { question: "Who painted 'The Starry Night'?", answer: "Vincent van Gogh" },
  { question: "What is the capital of Russia?", answer: "Moscow" },
  { question: "How many days are in a leap year?", answer: "366" },
  { question: "What is the largest country by area?", answer: "Russia" },
  { question: "Who wrote 'The Great Gatsby'?", answer: "F. Scott Fitzgerald" },
  { question: "What is the capital of Germany?", answer: "Berlin" },
  { question: "How many hearts does an octopus have?", answer: "3" },
  { question: "What is the chemical symbol for sodium?", answer: "Na" },
  { question: "Who discovered penicillin?", answer: "Alexander Fleming" },
  { question: "What is the capital of India?", answer: "New Delhi" },
  { question: "How many zeros are in a million?", answer: "6" },
  { question: "What is the largest species of shark?", answer: "Whale shark" },
  {
    question: "Who was the first woman to win a Nobel Prize?",
    answer: "Marie Curie",
  },
  { question: "What is the capital of Argentina?", answer: "Buenos Aires" },
  { question: "How many legs does a spider have?", answer: "8" },
  { question: "What is the chemical symbol for iron?", answer: "Fe" },
  { question: "Who wrote 'War and Peace'?", answer: "Leo Tolstoy" },
  { question: "What is the capital of South Africa?", answer: "Pretoria" },
  { question: "How many chromosomes do humans have?", answer: "46" },
  { question: "What is the fastest land animal?", answer: "Cheetah" },
  {
    question: "Who painted the ceiling of the Sistine Chapel?",
    answer: "Michelangelo",
  },
  { question: "What is the capital of Mexico?", answer: "Mexico City" },
  { question: "How many elements are in the periodic table?", answer: "118" },
  { question: "What is the largest bird?", answer: "Ostrich" },
  { question: "Who invented the light bulb?", answer: "Thomas Edison" },
  { question: "What is the capital of Egypt?", answer: "Cairo" },
  { question: "How many strings does a violin have?", answer: "4" },
  { question: "What is the chemical symbol for silver?", answer: "Ag" },
  { question: "Who wrote 'Pride and Prejudice'?", answer: "Jane Austen" },
  { question: "What is the capital of Brazil?", answer: "Brasília" },
  { question: "How many time zones are there in Russia?", answer: "11" },
  { question: "What is the largest lake in the world?", answer: "Caspian Sea" },
  { question: "Who composed 'The Four Seasons'?", answer: "Antonio Vivaldi" },
  { question: "What is the capital of South Korea?", answer: "Seoul" },
  {
    question: "How many bones are in a shark's body?",
    answer: "0 (cartilage)",
  },
  { question: "What is the chemical symbol for potassium?", answer: "K" },
  { question: "Who wrote 'The Odyssey'?", answer: "Homer" },
  { question: "What is the capital of Turkey?", answer: "Ankara" },
  { question: "How many rings are on the Olympic flag?", answer: "5" },
  {
    question: "What is the largest coral reef system?",
    answer: "Great Barrier Reef",
  },
  {
    question: "Who was the first female prime minister of the UK?",
    answer: "Margaret Thatcher",
  },
  { question: "What is the capital of Thailand?", answer: "Bangkok" },
  { question: "How many keys are on a standard piano?", answer: "88" },
  { question: "What is the chemical symbol for mercury?", answer: "Hg" },
  { question: "Who wrote 'The Catcher in the Rye'?", answer: "J.D. Salinger" },
  { question: "What is the capital of Sweden?", answer: "Stockholm" },
  { question: "How many US states are there?", answer: "50" },
  {
    question: "What is the smallest country in the world?",
    answer: "Vatican City",
  },
  { question: "Who discovered America?", answer: "Christopher Columbus" },
  { question: "What is the capital of Norway?", answer: "Oslo" },
  { question: "How many teeth does an adult human have?", answer: "32" },
  { question: "What is the chemical symbol for lead?", answer: "Pb" },
  { question: "Who wrote '1984'?", answer: "George Orwell" },
  { question: "What is the capital of Switzerland?", answer: "Bern" },
  { question: "How many stripes are on the US flag?", answer: "13" },
  { question: "What is the largest type of bear?", answer: "Polar bear" },
  { question: "Who was the first emperor of Rome?", answer: "Augustus" },
  { question: "What is the capital of Vietnam?", answer: "Hanoi" },
  { question: "How many amendments are in the US Constitution?", answer: "27" },
  { question: "What is the chemical symbol for carbon?", answer: "C" },
  { question: "Who wrote 'Moby Dick'?", answer: "Herman Melville" },
  { question: "What is the capital of Indonesia?", answer: "Jakarta" },
  { question: "How many stars are on the US flag?", answer: "50" },
  {
    question: "What is the largest moon in the solar system?",
    answer: "Ganymede",
  },
  {
    question: "Who was the first woman in space?",
    answer: "Valentina Tereshkova",
  },
  { question: "What is the capital of Greece?", answer: "Athens" },
];
